### ISSUE TITLE
Kurdish Translation Progress

### ISSUE THREAD

**Issue by tesseralis** [reactjs/ku.reactjs.org#1]
## Maintainer List

* @goran216
* @AlanHilal
* @HeroMohammed
## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Please take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, read the glossary and style guide (once they exist) to understand how to translate various technical and React-specific terms.

Please be prompt with your translations! If you find find that you can't commit any more, let the maintainers know so they can assign the page to someone else.

## For Maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

* [ ] Home Page (@tesseralis) #1

When PRs are merged, make sure to mark that page as completed!

## Core Pages

To do before releasing as an "official" translation. **Please translate these pages first.**

* [x] Home Page (@Goran216 ) #2 
* [ ] Tutorial (@aranfatih)

### Basics

* [ ] Hello World (@Kuchikill)
* [x] Introducing JSX (@broosk1993 ) #3
* [x] Rendering Elements (@brwasalam) #18 
* [x] Components and Props (@layik) #5 
* [ ] State and Lifecycle ( @broosk1993)
* [x] Handling Events (@HeroMohammed )#10
* [ ] Conditional Rendering (@Goran216 )
* [x] Lists and Keys (@BisarOmer) #15 
* [ ] Forms (@HeroMohammed)
* [ ] Lifting State Up (@arduiShko)
* [ ] Composition vs Inheritance (@Dnya-S)
* [ ] Thinking in React (@layik)

### API Reference

* [ ] React (@dashty94)
* [ ] React.Component (@BisarOmer)
* [ ] ReactDOM (@brwasalam )
* [ ] ReactDOMServer (@brwasalam)
* [ ] DOM Elements
* [ ] SyntheticEvent
* [ ] Test Utilities
* [ ] Shallow Renderer
* [ ] Test Renderer
* [ ] JS Environment Requirements
* [ ] Glossary

### Navigation

These are the navigation links that appears in the sidebar. Possibly wait until
the corresponding sections are translated to do these.

* [ ] tutorial/nav.yml
* [ ] docs/nav.yml

## Next Steps

These are the next most important translations, ordered by importance:

### Installation

* [ ] Getting Started
* [ ] Add React to a Website
* [ ] Create a New React App
* [ ] CDN Links

### Hooks

Everyone is hooked on hooks! People are really excited for these and it would be great for them to be translated.

  * [ ] Introducing Hooks
  * [ ] Hooks at a Glance
  * [ ] Using the State Hook
  * [ ] Using the Effect Hook
  * [ ] Rules of Hooks
  * [ ] Building Your Own Hooks
  * [ ] Hooks API Reference
  * [ ] Hooks FAQ

### Warnings

These are the pages that you get when you click the links in the console (e.g. https://reactjs.org/warnings/dont-call-proptypes.html). People tend to search these, so **please don't translate the error message itself**.
 
* [ ] dont-call-proptypes
* [ ] invalid-aria-prop
* [ ] invalid-hook-call-warning
* [ ] legacy-factories
* [ ] refs-must-have-owner
* [ ] special-props
* [ ] unknown-prop

### Advanced Guides

* [ ] Accessibility
* [ ] Code-Splitting
* [ ] Context
* [ ] Error Boundaries
* [ ] Forwarding Refs
* [ ] Fragments
* [ ] Higher-Order Components
* [ ] Integrating with Other Libraries
* [ ] JSX In Depth
* [ ] Optimizing Performance
* [ ] Portals
* [ ] React Without ES6
* [ ] React Without JSX
* [ ] Reconciliation
* [ ] Refs and the DOM
* [ ] Render Props
* [ ] Static Type Checking
* [ ] Strict Mode
* [ ] Typechecking With PropTypes
* [ ] Uncontrolled Components
* [ ] Web Components

### FAQ

* [ ] APIs and AJAX
* [ ] Babel, JSX, and Build Steps
* [ ] Passing Functions to Components
* [ ] Component State
* [ ] Styling and CSS
* [ ] File Structure
* [ ] Versioning Policy
* [ ] Virtual DOM and Internals

### Contributing

Priority: Low

* [ ] How to Contribute
* [ ] Codebase Overview
* [ ] Implementation Notes
* [ ] Design Principles

### Components

Components in `src/components` that have some text in them.

* [ ] CodeEditor
* [ ] CodeExample
* [ ] ErrorDecoder
* [ ] LayoutFooter
* [ ] LayoutHeader
* [ ] MarkdownPage

## Additional Translations

These are not the primary translation targets.

* [ ] Blog
* [ ] Community

**Comment by tesseralis** [comment]
@Goran216 @AlanHilal @HeroMohammed please use this issue to keep track of your progress. Let me know if you need help or have any questions!

**Comment by Goran216** [comment]
@HeroMohammed I was thinking if you could share this with HackaSuli members at one of the meetups, we would get more contributors and proceed faster. What do you think?

**Comment by HeroMohammed** [comment]
@Goran216  I shared this with HackaSuly community and now we have @aranfatih and @Kuchikill on board!

**Comment by Goran216** [comment]
Thanks a lot. 👍

**Comment by layik** [comment]
Great work everybody! ڕیئاکت

**Comment by broosk1993** [comment]
Great work everyone. How the translation markdowns are distributed? Shall pick one myself or there a certain approach? In the case of the former, I would love to pick "Introducing JSX".

**Comment by HeroMohammed** [comment]
> Great work everyone. How the translation markdowns are distributed? Shall I pick one myself or there's a certain approach? In the case of the former, I would love to pick "Introducing JSX".

Great, I added you to Introducing JSX. Clone the repo, translate your page, and submit a pull request!

**Comment by broosk1993** [comment]
Great, Hero.

Just for the reference, I use the zKurd IT dictionary. As agreed upon, we can discuss the standardization later. Here's a link for anyone interested:

http://zkurd.org/?Besh=Ferheng

**Comment by Goran216** [comment]
@broosk1993 @HeroMohammed Not sure if it will make a big change but I am using Sorani Kurdish keyboard on mac. I guess if you run the app locally and everything look fine then you should be ok.

**Comment by Goran216** [comment]
Just a note for anyone contributing. If you couldn't find the right Kurdish translation for any word, just use the same word but written in Kurdish. Like you can translate 'Method' to 'مێسۆد'. At least for now that is fine, we can later improve it.

**Comment by dolanskurd** [comment]
Good job guys. ;-)

**Comment by broosk1993** [comment]
@HeroMohammed @Goran216  I need write access to the repo please. The repo responds with 403 unauthorized when pushing the new branch.

**Comment by layik** [comment]
Push to your own fork/repo master or branch then create the PR from there upstream Kak @broosk1993

**Comment by broosk1993** [comment]
> Push to your own fork/repo master or branch then create the PR from there upstream Kak @broosk1993

Thanks. Will do

**Comment by broosk1993** [comment]
> Push to your own fork/repo master or branch then create the PR from there upstream Kak @broosk1993

It worked. Thanks again.

**Comment by HeroMohammed** [comment]
@broosk1993 I suggest you delete the English text. We can always refer to the English website for comparison.

**Comment by layik** [comment]
Hope it's not a duplicate but started without asking `Components and props`, will send the PR when ready.

https://github.com/reactjs/ku.reactjs.org/commit/ff73f7c25d991a95bd90ffc32048ad095ee504c3

**Comment by Goran216** [comment]
@HeroMohammed to keep the workflow consistent, I recommend making a branch for any page you work on, then merging it to master with a pull request. It's better not to push directly to master. 

PS; you could merge without pull request too (if you have permission) but you need to make sure that it will not be a fast-forward merge and a commit message is inserted. For that, if you are merging from terminal, you need to include --no-ff'. For ex. 'git merge homepage --no-ff'. This will ask you to include a commit message which is exactly same as doing it through pull request.

Thanks,

**Comment by broosk1993** [comment]
Please add me to "State and Lifecycle"

**Comment by dolanskurd** [comment]
Also I recommend to use provided Kurdish (and other) dictionaries in my repo for helping in translating process along with a great work (Wîkîferheng: https://ku.m.wiktionary.org/wiki/Destpêk) made by my friends.

**Comment by Goran216** [comment]
Our progress can be tracked from https://isreacttranslatedyet.com.

**Comment by tesseralis** [comment]
Hey everyone! How are your translations going?

**Comment by HeroMohammed** [comment]
> Hey everyone! How are your translations going?

@Goran216 @broosk1993 @aranfatih @brwasalam @BisarOmer

**Comment by Goran216** [comment]
Hey,

I am on vacation and will be back on 1/4/2019

Best,

**Comment by bryar323** [comment]
good job

**Comment by Dnya-S** [comment]
hello everyone I am new ,and as a start I would like to translate Introducing Hooks!

**Comment by HeroMohammed** [comment]
> hello everyone I am new ,and as a start I would like to translate Introducing Hooks!

Hi @Dnya-S !

Welcome and thanks for contributing. We need to first start from the core pages. I already assigned you to the Composition vs Inheritance page. Please let me know if you would prefer any other page from the Core Pages.

**Comment by layik** [comment]
OK, I like thinking in React so reserve `Thinking in React` for me :)

**Comment by BisarOmer** [comment]
Hello, I will be working on React.Component

**Comment by tesseralis** [comment]
Hey @Goran216, @AlanHilal, @HeroMohammed, how is it going? It doesn't seem like there's been updates here for a while. Please let me know if you need help maintaining the repo.

**Comment by Goran216** [comment]
Hi @tesseralis 
I've been a bit busy lately but will try to contribute more often soon.

**Comment by hewasalam** [comment]
Hello Everybody
I am Kurdish language lecture but not very familiar with this website. currently, we have done a great work and translated OJS. So, if you think I can help here please let me know. Also, what would be the output? 
You may see our work here:
https://translate.pkp.sfu.ca/languages/
Regards,
Hewa

**Comment by gaearon** [comment]
I'm going to archive this repo as it's not actively maintained, and the translation has stalled.
